### PR TITLE
ray: Fix ray/box intersection on systems without isnanf

### PR DESCRIPTION
**Pull request by sbstnk**
Fixes https://github.com/ebassi/graphene/issues/223

Proposed changes:

 - Fix the typo in the non-`HAVE_ISNANF` code path to match the behavior of the `HAVE_ISNANF` code path.

### CODE REVIEW

**Comment by Gottox** [comment]
It would be awesome to add a testcase for this issue.

**Comment by ebassi** [comment]
Indeed, it would be awesome to have a test case. :-)

**Comment by ericonr** [comment]
I think merging this as a simple patch is reasonable, but I would recommend going with https://github.com/ebassi/graphene/pull/225 later. I can rebase it.

**Comment by sbstnk** [comment]
I wasn't sure about adding a test case, because due to the nature of the bug that would just be some *random* numbers for which it happens to fail instead of a real class of issues. But I can add the example from the bug report as a test. Can't think of a good name for such a test though.

**Comment by sbstnk** [comment]
I was thinking of turning the code I used to find these random numbers into a test that does picking for ~1000 random coordinates like it would be done in clutter/mutter. Not sure how useful such non-deterministic tests would be though.

**Comment by sbstnk** [comment]
I couldn't find a way to make a useful test with random positions, so I went with some hardcoded ones.

This includes code based on Mutter/Clutter which was written by @GeorgesStavracas. Since Mutter is GPL and graphene is MIT, are you okay with using that code under MIT @GeorgesStavracas?

**Comment by GeorgesStavracas** [comment]
I'm fine with it :slightly_smiling_face:

**Comment by ebassi** [comment]
I think both #225 and #220 have fixed most of these issues.

**Comment by sbstnk** [comment]
Would it make sense to open a separate PR with just the test since a test was specifically requested here and the merged fix did not have one?

**Comment by ebassi** [comment]
Yes, sure.

**Pull request closed without merging**
